# -*- coding: utf-8 -*-
"""Model_train_collab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHwHF46g_ubmS8Jbma9E3v4_3QiZYk_b
"""

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive"

DATA_PATH = "/content/drive/MyDrive/amazon_multi_dataset"

!ls "$DATA_PATH"

import os
from datasets import load_dataset, concatenate_datasets

DATA_PATH = "/content/drive/MyDrive/amazon_multi_dataset"
langs = ["en", "es", "fr", "de"]

def load_split(split):
    datasets = []
    for lang in langs:
        jsonl_file = f"{DATA_PATH}/{lang}/{split}.jsonl"
        json_file = f"{DATA_PATH}/{lang}/{split}.json"

        # Detect file
        if os.path.exists(jsonl_file):
            file = jsonl_file
        elif os.path.exists(json_file):
            file = json_file
        else:
            print(f"⚠️ No {split} file for {lang}. Will generate split automatically.")
            file = None

        if file:
            print(f"📂 Loading: {file}")
            ds = load_dataset("json", data_files=file, split="train")
        else:
            # Create validation from train
            train_file_jsonl = f"{DATA_PATH}/{lang}/train.jsonl"
            train_file_json = f"{DATA_PATH}/{lang}/train.json"

            # Detect train file
            train_file = train_file_jsonl if os.path.exists(train_file_jsonl) else train_file_json
            print(f"📂 Creating {split} for {lang} from: {train_file}")

            full_train = load_dataset("json", data_files=train_file, split="train")
            full_train = full_train.train_test_split(test_size=0.1)  # 10% for val.

            if split == "validation":
                ds = full_train["test"]
            else:
                ds = full_train["train"]

        # Add language column
        ds = ds.add_column("language", [lang] * len(ds))
        datasets.append(ds)

    return concatenate_datasets(datasets)

# Load datasets with automatic fixing for missing validation
train_ds = load_split("train")
val_ds = load_split("validation")
test_ds = load_split("test")

train_ds, val_ds, test_ds

from transformers import XLMRobertaTokenizerFast

MODEL_NAME = "xlm-roberta-base"
tokenizer = XLMRobertaTokenizerFast.from_pretrained(MODEL_NAME)

def tokenize_batch(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",  # Use fixed length for training
        max_length=128
    )

train_ds_tokenized = train_ds.map(tokenize_batch, batched=True)
val_ds_tokenized = val_ds.map(tokenize_batch, batched=True)
test_ds_tokenized = test_ds.map(tokenize_batch, batched=True)

train_ds_tokenized, val_ds_tokenized, test_ds_tokenized

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/xlm_roberta_sentiment",
    eval_strategy="epoch",              # updated parameter name
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=200,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none"
)

print("Train labels:", set(train_ds_tokenized["label"]))
print("Val labels:", set(val_ds_tokenized["label"]))
print("Test labels:", set(test_ds_tokenized["label"]))

def normalize_labels(example):
    if example["label"] <= 1:   # original 0 or 1 -> Negative
        return {"label": 0}
    elif example["label"] == 2: # original 2 -> Neutral
        return {"label": 1}
    else:                       # original 3 or 4 -> Positive
        return {"label": 2}

train_ds = train_ds.map(normalize_labels)
val_ds   = val_ds.map(normalize_labels)
test_ds  = test_ds.map(normalize_labels)

print("Train:", set(train_ds["label"]))
print("Val:", set(val_ds["label"]))
print("Test:", set(test_ds["label"]))

from transformers import XLMRobertaTokenizerFast

tokenizer = XLMRobertaTokenizerFast.from_pretrained("xlm-roberta-base")

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

train_ds = train_ds.map(tokenize, batched=True)
val_ds = val_ds.map(tokenize, batched=True)
test_ds = test_ds.map(tokenize, batched=True)

cols = ["text", "language", "id", "label_text"]

for col in cols:
    if col in train_ds.column_names:
        train_ds = train_ds.remove_columns(col)
        val_ds = val_ds.remove_columns(col)
        test_ds = test_ds.remove_columns(col)

train_small = train_ds.shuffle(seed=42).select(range(100000)) # use 100k instead of 800k
val_small   = val_ds.shuffle(seed=42).select(range(20000))    # reduce validation

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_small,
    eval_dataset=val_small,
    compute_metrics=compute_metrics,
)

from transformers import pipeline

sentiment_model = pipeline("text-classification", model=model, tokenizer=tokenizer)

examples = [
    "I love this product! It works perfectly 😍",
    "This item is terrible and broke after one day 😡",
    "It’s okay, not bad but not great either."
]

for text in examples:
    print(text, "→", sentiment_model(text)[0])

test_results = trainer.evaluate(test_ds)
test_results

model.save_pretrained("/content/drive/MyDrive/sentiment_model")
tokenizer.save_pretrained("/content/drive/MyDrive/sentiment_model")

from transformers import pipeline, XLMRobertaTokenizerFast, XLMRobertaForSequenceClassification

MODEL_PATH = "/content/drive/MyDrive/sentiment_model"

tokenizer = XLMRobertaTokenizerFast.from_pretrained(MODEL_PATH)
model = XLMRobertaForSequenceClassification.from_pretrained(MODEL_PATH)

classifier = pipeline("text-classification", model=model, tokenizer=tokenizer)

test_output = classifier("This is great!")
print(test_output)

import gradio as gr

label_map = {
    0: "Negative 😡",
    1: "Neutral 😐",
    2: "Positive 😊"
}

def predict(text):
    try:
        res = classifier(text)[0]

        # Fix label conversion safely
        label_raw = res["label"]

        if isinstance(label_raw, str) and "LABEL" in label_raw:
            label_id = int(label_raw.replace("LABEL_", ""))
        else:
            label_id = int(label_raw)

        confidence = round(float(res["score"]), 2)

        return f"{label_map[label_id]} (Confidence: {confidence})"

    except Exception as e:
        return f"⚠️ Error: {str(e)}"


demo = gr.Interface(
    fn=predict,
    inputs=gr.Textbox(lines=3, placeholder="Type your sentence here..."),
    outputs="text",
    title="🌍 Multilingual Sentiment Analyzer"
)

demo.launch()